---
apiVersion: helm.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: target
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: target
      key: config