---
apiVersion: resources.stuttgart-things.com/v1alpha1
kind: VolumeClaim
metadata:
  name: simple-storage
  namespace: default
spec:
  providerConfigRef: dev
  annotations:
    description: "A simple persistent volume claim for application data"
  pvcName: app-data
  namespace: default
  storageClassName: standard
  storage: "1Gi"
