---
apiVersion: helm.m.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: target
  namespace: default
spec:
  credentials:
    secretRef:
      key: config
      name: target
      namespace: crossplane-system
    source: Secret
