---
apiVersion: helm.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: target
spec:
  credentials:
    secretRef:
      key: config
      name: target
      namespace: crossplane-system
    source: Secret
