---
apiVersion: helm.m.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: in-cluster
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: in-cluster
      key: config
